server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/commerce?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "rnjswnsgur12!!"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update